'use client'

import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { Download, RefreshCw, Crown, Target, Users, Zap } from 'lucide-react'
import { ReportCard as ReportCardType } from '@/types'
import { CommitmentScore } from '@/lib/commitment/scoring-engine'

interface PremiumReportCardProps {
  report: ReportCardType
  commitmentScore: CommitmentScore
  onRestart: () => void
  answers?: any[] // Add answers to pass to progression API
}

export default function PremiumReportCard({ 
  report, 
  commitmentScore, 
  onRestart,
  answers = []
}: PremiumReportCardProps) {
  const [progressionGuidance, setProgressionGuidance] = useState<string>('')
  const [isLoadingProgression, setIsLoadingProgression] = useState(false)
  const [progressionData, setProgressionData] = useState<{
    pointsNeeded: number
    targetScore: number
    nextLevel: string
  } | null>(null)

  useEffect(() => {
    // Only fetch progression guidance if not at max level and have answers
    if (commitmentScore.level !== 'Visionary' && answers.length > 0) {
      fetchProgressionGuidance()
    }
  }, [commitmentScore, answers])

  const fetchProgressionGuidance = async () => {
    if (isLoadingProgression) {
      console.log('Progression guidance already loading, skipping')
      return
    }
    
    setIsLoadingProgression(true)
    try {
      const response = await fetch('/api/generate-progression', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          answers, 
          commitmentScore 
        })
      })
      
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`)
      }
      
      const data = await response.json()
      
      if (data.guidance) {
        setProgressionGuidance(data.guidance)
        setProgressionData({
          pointsNeeded: data.pointsNeeded,
          targetScore: data.targetScore,
          nextLevel: data.nextLevel
        })
      } else {
        throw new Error('No guidance received from API')
      }
    } catch (error) {
      console.error('Error fetching progression guidance:', error)
      // Set fallback guidance
      setProgressionGuidance(getFallbackProgressionText())
      setProgressionData({
        pointsNeeded: Math.max(0, getTargetScore() - commitmentScore.finalScore),
        targetScore: getTargetScore(),
        nextLevel: getNextLevel()
      })
    } finally {
      setIsLoadingProgression(false)
    }
  }
  
  const getTargetScore = () => {
    switch (commitmentScore.level) {
      case 'Explorer': return 25
      case 'Advocate': return 45
      case 'Catalyst': return 70
      default: return 70
    }
  }
  
  const getNextLevel = () => {
    switch (commitmentScore.level) {
      case 'Explorer': return 'Advocate'
      case 'Advocate': return 'Catalyst' 
      case 'Catalyst': return 'Visionary'
      default: return 'Visionary'
    }
  }

  const getFallbackProgressionText = () => {
    switch (commitmentScore.level) {
      case 'Explorer':
        return "Focus on building consistent daily sustainability practices and making more conscious consumption choices."
      case 'Advocate':
        return "Expand your influence by sharing knowledge, leading initiatives, and inspiring others in your community."
      case 'Catalyst':
        return "Drive systemic change through large-scale initiatives, partnerships, and transformational leadership."
      default:
        return "Continue leading transformational change in your sphere of influence."
    }
  }
  
  const handleDownloadReport = () => {
    // Create a clean version of the report for download
    const reportContent = `
SUSTAINABILITY ASSESSMENT REPORT
===============================

Personal Profile: ${commitmentScore.level}
Overall Score: ${commitmentScore.finalScore}
Assessment Date: ${new Date().toLocaleDateString()}

PROFILE DESCRIPTION
${getLevelDescription(commitmentScore.level)}

SUSTAINABILITY SCORES
- Action Velocity: ${Math.round(commitmentScore.actionVelocity * 100)}%
- Resource Allocation: ${Math.round(commitmentScore.resourceAllocation * 100)}%  
- Influence Radius: ${Math.round(commitmentScore.influenceRadius * 100)}%
- Commitment Intensity: ${Math.round(commitmentScore.commitmentIntensity * 100)}%

CATEGORY BREAKDOWN
${report.categories?.map(cat => `- ${cat.name}: ${cat.score}% - ${cat.description}`).join('\n') || 'No categories available'}

KEY INSIGHTS
${report.insights.map((insight, i) => `${i + 1}. ${insight}`).join('\n')}

RECOMMENDED ACTIONS
${report.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

PERSONALITY PROFILE
${report.personalityProfile}

Generated by Sustainability Assessment Tool
    `.trim()

    // Create and download the file
    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `sustainability-report-${commitmentScore.level.toLowerCase()}-${new Date().toISOString().slice(0, 10)}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    window.URL.revokeObjectURL(url)
  }
  
  const getLevelIcon = (level: string) => {
    switch (level) {
      case 'Visionary': return Crown
      case 'Catalyst': return Zap
      case 'Advocate': return Target
      case 'Explorer': return Users
      default: return Target
    }
  }
  
  const getLevelColor = (level: string) => {
    switch (level) {
      case 'Visionary': return 'from-accent-gold to-earth-clay'
      case 'Catalyst': return 'from-forest-700 to-forest-600'
      case 'Advocate': return 'from-earth-clay to-earth-terracotta'
      case 'Explorer': return 'from-forest-600 to-forest-500'
      default: return 'from-forest-700 to-forest-600'
    }
  }
  
  const getLevelDescription = (level: string) => {
    switch (level) {
      case 'Visionary': return 'Systemic change maker ready to transform industries'
      case 'Catalyst': return 'Natural leader prepared to influence meaningful change'
      case 'Advocate': return 'Personally committed to sustainable transformation'
      case 'Explorer': return 'Curious mind beginning the sustainability journey'
      default: return 'Sustainability-conscious individual'
    }
  }

  const LevelIcon = getLevelIcon(commitmentScore.level)

  return (
    <div className="fixed inset-0 bg-gradient-dawn overflow-y-auto">
      <div className="min-h-screen flex items-start sm:items-center justify-center px-3 sm:px-6 py-4 sm:py-6">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.8 }}
          className="w-full max-w-4xl"
        >
          <div className="bg-white/80 backdrop-blur-sm rounded-2xl sm:rounded-3xl premium-shadow border border-white/20 overflow-hidden">
            
            {/* Header Section */}
            <div className={`bg-gradient-to-r ${getLevelColor(commitmentScore.level)} p-4 sm:p6 md:p-8 text-accent-pearl relative overflow-hidden`}>
              <div className="absolute inset-0 bg-black/10" />
              <div className="relative z-10">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-4 gap-3 sm:gap-0">
                  <div className="flex items-center gap-2 sm:gap-3">
                    <LevelIcon className="w-6 h-6 sm:w-8 sm:h-8" />
                    <span className="font-mono text-xs sm:text-sm uppercase tracking-widest opacity-90">
                      Commitment Level
                    </span>
                  </div>
                  <div className="text-left sm:text-right">
                    <div className="text-2xl sm:text-3xl font-serif font-bold">
                      {commitmentScore.finalScore}
                    </div>
                    <div className="text-xs sm:text-sm opacity-90">Overall Score</div>
                  </div>
                </div>
                
                <h1 className="font-serif text-2xl sm:text-3xl md:text-4xl font-bold mb-2">
                  {commitmentScore.level}
                </h1>
                <p className="text-base sm:text-lg md:text-xl opacity-90 leading-relaxed">
                  {getLevelDescription(commitmentScore.level)}
                </p>
              </div>
            </div>

            {/* Main Content */}
            <div className="p-4 sm:p-6 md:p-8 space-y-6 sm:space-y-8">
              
              {/* Commitment Dimensions */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {[
                  { label: 'Action Velocity', value: commitmentScore.actionVelocity, icon: Zap },
                  { label: 'Resource Allocation', value: commitmentScore.resourceAllocation, icon: Target },
                  { label: 'Influence Radius', value: commitmentScore.influenceRadius, icon: Users },
                  { label: 'Commitment Intensity', value: commitmentScore.commitmentIntensity, icon: Crown }
                ].map((dimension, index) => (
                  <motion.div
                    key={dimension.label}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 + index * 0.1 }}
                    className="bg-accent-mist rounded-2xl p-4 text-center"
                  >
                    <dimension.icon className="w-6 h-6 text-forest-700 mx-auto mb-2" />
                    <div className="text-2xl font-serif font-bold text-forest-900 mb-1">
                      {Math.round(dimension.value * 100)}
                    </div>
                    <div className="text-xs text-earth-stone font-medium">
                      {dimension.label}
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* Categories */}
              <div className="space-y-4">
                <h3 className="font-serif text-xl text-forest-900 mb-4">Sustainability Profile</h3>
                <div className="grid md:grid-cols-2 gap-4">
                  {report.categories?.map((category, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.4 + index * 0.1 }}
                      className="bg-accent-mist rounded-xl p-5"
                    >
                      <div className="flex justify-between items-center mb-3">
                        <h4 className="font-medium text-forest-900">{category.name}</h4>
                        <span className="font-bold text-forest-700 text-lg">
                          {category.score}%
                        </span>
                      </div>
                      <div className="h-2 bg-earth-sand/50 rounded-full overflow-hidden mb-3">
                        <motion.div
                          initial={{ width: 0 }}
                          animate={{ width: `${category.score}%` }}
                          transition={{ delay: 0.6 + index * 0.1, duration: 0.8 }}
                          className="h-full bg-gradient-to-r from-forest-700 to-earth-clay"
                        />
                      </div>
                      <p className="text-xs text-earth-stone leading-relaxed">
                        {category.description}
                      </p>
                    </motion.div>
                  ))}
                </div>
              </div>

              {/* Sustainability Profile Journey */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.7 }}
                className="space-y-4"
              >
                <h3 className="font-serif text-xl text-forest-900 mb-6">Your Sustainability Journey</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  {[
                    { 
                      level: 'Explorer', 
                      range: '0-24', 
                      icon: Users, 
                      color: 'from-earth-sand to-earth-clay',
                      description: 'Curious mind beginning the sustainability journey'
                    },
                    { 
                      level: 'Advocate', 
                      range: '25-44', 
                      icon: Target, 
                      color: 'from-earth-clay to-earth-terracotta',
                      description: 'Personally committed to sustainable transformation'
                    },
                    { 
                      level: 'Catalyst', 
                      range: '45-69', 
                      icon: Zap, 
                      color: 'from-forest-700 to-forest-600',
                      description: 'Natural leader prepared to influence meaningful change'
                    },
                    { 
                      level: 'Visionary', 
                      range: '70+', 
                      icon: Crown, 
                      color: 'from-accent-gold to-earth-clay',
                      description: 'Systemic change maker ready to transform industries'
                    }
                  ].map((profile, index) => {
                    const ProfileIcon = profile.icon
                    const isCurrentLevel = profile.level === commitmentScore.level
                    
                    return (
                      <motion.div
                        key={profile.level}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.8 + index * 0.1 }}
                        className={`relative rounded-xl p-4 border-2 transition-all duration-300 ${
                          isCurrentLevel 
                            ? 'border-forest-700 bg-forest-50 shadow-lg' 
                            : 'border-earth-sand/50 bg-white/50 hover:border-forest-500/50'
                        }`}
                      >
                        {isCurrentLevel && (
                          <div className="absolute -top-2 -right-2 w-6 h-6 bg-forest-700 text-accent-pearl rounded-full flex items-center justify-center text-xs font-bold">
                            ✓
                          </div>
                        )}
                        
                        <div className={`w-8 h-8 rounded-full bg-gradient-to-r ${profile.color} flex items-center justify-center mb-3`}>
                          <ProfileIcon className="w-4 h-4 text-white" />
                        </div>
                        
                        <h4 className={`font-serif text-sm font-bold mb-1 ${
                          isCurrentLevel ? 'text-forest-900' : 'text-earth-stone'
                        }`}>
                          {profile.level}
                        </h4>
                        
                        <div className={`text-xs mb-2 font-mono ${
                          isCurrentLevel ? 'text-forest-700' : 'text-earth-stone/70'
                        }`}>
                          Score: {profile.range}
                        </div>
                        
                        <p className={`text-xs leading-relaxed ${
                          isCurrentLevel ? 'text-earth-ash' : 'text-earth-stone/80'
                        }`}>
                          {profile.description}
                        </p>
                        
                        {isCurrentLevel && (
                          <div className="mt-3 text-xs text-forest-700 font-medium">
                            You are here
                          </div>
                        )}
                      </motion.div>
                    )
                  })}
                </div>
                
                {/* AI-Powered Progression Path */}
                {commitmentScore.level !== 'Visionary' && (
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 1.2 }}
                    className="bg-accent-mist rounded-xl p-4 mt-4"
                  >
                    <h4 className="font-serif text-sm font-bold text-forest-900 mb-2">
                      🌱 Your Personalized Path Forward
                    </h4>
                    
                    {isLoadingProgression ? (
                      <div className="flex items-center gap-2 text-xs text-earth-ash">
                        <div className="w-3 h-3 border border-forest-700/30 border-t-forest-700 rounded-full animate-spin"></div>
                        Generating personalized guidance...
                      </div>
                    ) : (
                      <>
                        <p className="text-xs text-earth-ash mb-2 leading-relaxed">
                          {progressionGuidance || getFallbackProgressionText()}
                        </p>
                        <div className="text-xs text-forest-700 font-medium">
                          Current score: {commitmentScore.finalScore} | 
                          Next level: {progressionData?.nextLevel || 'Advance'} ({progressionData?.targetScore || 'Higher'}{progressionData?.targetScore ? '+' : ''} points)
                          {progressionData?.pointsNeeded && progressionData.pointsNeeded > 0 && 
                            ` | Need ${progressionData.pointsNeeded} more points`
                          }
                        </div>
                      </>
                    )}
                  </motion.div>
                )}
              </motion.div>

              {/* Personality Profile */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 1.3 }}
                className="bg-forest-50 rounded-2xl p-6"
              >
                <h3 className="font-serif text-xl text-forest-900 mb-4">Your Sustainability Personality</h3>
                <p className="text-earth-ash leading-relaxed">{report.personalityProfile}</p>
              </motion.div>

              {/* Insights & Recommendations */}
              <div className="grid md:grid-cols-2 gap-6">
                <motion.div
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 1.4 }}
                >
                  <h3 className="font-serif text-lg text-forest-900 mb-4">Key Insights</h3>
                  <ul className="space-y-3">
                    {report.insights.map((insight, index) => (
                      <li key={index} className="flex items-start gap-2">
                        <div className="w-1.5 h-1.5 bg-forest-700 rounded-full mt-2 flex-shrink-0" />
                        <span className="text-sm text-earth-ash leading-relaxed">{insight}</span>
                      </li>
                    ))}
                  </ul>
                </motion.div>

                <motion.div
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 1.5 }}
                >
                  <h3 className="font-serif text-lg text-forest-900 mb-4">Next Actions</h3>
                  <ul className="space-y-3">
                    {report.recommendations.map((recommendation, index) => (
                      <li key={index} className="flex items-start gap-2">
                        <div className="w-5 h-5 bg-forest-700 text-accent-pearl rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">
                          {index + 1}
                        </div>
                        <span className="text-sm text-earth-ash leading-relaxed">{recommendation}</span>
                      </li>
                    ))}
                  </ul>
                </motion.div>
              </div>

              {/* Level-Specific Call to Action */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 1.4 }}
                className={`bg-gradient-to-r ${getLevelColor(commitmentScore.level)} rounded-2xl p-6 text-accent-pearl relative overflow-hidden`}
              >
                <div className="absolute inset-0 bg-black/10" />
                <div className="relative z-10">
                  <h3 className="font-serif text-xl mb-2">
                    {commitmentScore.level === 'Visionary' && "Transform the World"}
                    {commitmentScore.level === 'Catalyst' && "Lead the Change"}
                    {commitmentScore.level === 'Advocate' && "Amplify Your Impact"}
                    {commitmentScore.level === 'Explorer' && "Begin Your Journey"}
                  </h3>
                  <p className="mb-4 opacity-90">
                    {commitmentScore.level === 'Visionary' && 
                      "You're ready for transformational partnerships. Let's discuss exclusive opportunities for systemic change."}
                    {commitmentScore.level === 'Catalyst' && 
                      "Your leadership potential is clear. Explore programs designed for change-makers like you."}
                    {commitmentScore.level === 'Advocate' && 
                      "Your personal commitment shines through. Join a community of like-minded advocates."}
                    {commitmentScore.level === 'Explorer' && 
                      "Your curiosity is the first step. Continue your journey with curated learning experiences."}
                  </p>
                  <div className="flex gap-3">
                    <button className="px-4 py-2 bg-white/20 rounded-lg text-sm font-medium hover:bg-white/30 transition-colors">
                      Learn More
                    </button>
                    <button className="px-4 py-2 bg-accent-pearl text-forest-900 rounded-lg text-sm font-medium hover:bg-accent-mist transition-colors">
                      Get Started
                    </button>
                  </div>
                </div>
              </motion.div>

              {/* Actions */}
              <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center pt-4">
                <motion.button
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  onClick={onRestart}
                  className="flex items-center justify-center gap-2 px-6 py-3 bg-earth-sand text-earth-ash rounded-full font-medium text-sm hover:bg-earth-stone/20 transition-colors min-h-[48px] touch-manipulation"
                >
                  <RefreshCw className="w-4 h-4" />
                  <span className="hidden sm:inline">Retake Assessment</span>
                  <span className="sm:hidden">Retake</span>
                </motion.button>
                <motion.button
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  onClick={handleDownloadReport}
                  className="flex items-center justify-center gap-2 px-6 py-3 bg-forest-900 text-accent-pearl rounded-full font-medium text-sm hover:bg-forest-800 transition-colors min-h-[48px] touch-manipulation"
                >
                  <Download className="w-4 h-4" />
                  <span className="hidden sm:inline">Download Report</span>
                  <span className="sm:hidden">Download</span>
                </motion.button>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  )
}